AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  s3websitebucket:
    Type: AWS::S3::Bucket
    Properties:
      # AccessControl ?
      BucketName: digitizetest.aleonard.dev
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Project
          Value: Digitize
        - Key: Purpose
          Value: DigitizeFrontendS3Bucket
  s3websitebucketpolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3websitebucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: arn:aws:s3:::digitizetest.aleonard.dev/*
            Principal: "*"
